'use strict';
const KEY = 'campusgrade_students_v1';
const $ = id => document.getElementById(id);
const subjects = [['web','Web Development'],['db','Database Systems'],['js','JavaScript Programming']];
function load(){try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(data)?data:[]}catch{return []}}
function save(records){localStorage.setItem(KEY,JSON.stringify(records))}
function node(tag,text){const element=document.createElement(tag);element.textContent=text;return element}
function showResult(student){$('result').hidden=false;$('resultDate').textContent=student.date;$('resultIdentity').textContent=`${student.name} · Roll: ${student.roll} · ${student.course}`;$('resultSubjects').replaceChildren();student.subjects.forEach(s=>$('resultSubjects').append(node('p',`${s.name}: ${s.marks} / 100`)));$('total').textContent=`${student.total} / 300`;$('percentage').textContent=`${student.percentage}%`;$('status').textContent=student.status;$('status').className=student.status==='Pass'?'pass':'fail';}
function render(){const query=$('search').value.trim().toLowerCase();const all=load();const filtered=all.filter(s=>s.name.toLowerCase().includes(query)||s.roll.toLowerCase().includes(query));$('count').textContent=`${all.length} saved`;$('records').replaceChildren();if(!filtered.length){$('records').append(node('p','No matching student records.'));return}filtered.forEach(s=>{const card=node('article','');card.className='record';const info=node('div','');info.append(node('strong',`${s.name} (${s.roll})`),node('p',`${s.course} · ${s.percentage}% · ${s.status}`));const controls=node('div','');const view=node('button','View');view.type='button';view.onclick=()=>{showResult(s);$('result').scrollIntoView({behavior:'smooth'})};const remove=node('button','Delete');remove.type='button';remove.className='danger';remove.onclick=()=>{if(confirm(`Delete result for ${s.name}?`)){save(load().filter(item=>item.id!==s.id));render()}};controls.append(view,remove);card.append(info,controls);$('records').append(card)})}
$('studentForm').addEventListener('submit',event=>{event.preventDefault();$('error').textContent='';const name=$('name').value.trim(),roll=$('roll').value.trim(),course=$('course').value.trim();if(!name||!roll||!course){$('error').textContent='Enter name, roll number and course.';return}const marks=[];for(const [id,label] of subjects){const raw=$(id).value.trim();const number=Number(raw);if(raw===''||!Number.isInteger(number)||number<0||number>100){$('error').textContent=`Enter a whole number from 0 to 100 for ${label}.`;return}marks.push({name:label,marks:number})}const all=load();if(all.some(s=>s.roll.toLowerCase()===roll.toLowerCase())){$('error').textContent='This roll number already exists. Delete its previous record first.';return}const total=marks.reduce((sum,s)=>sum+s.marks,0);const student={id:`${Date.now()}-${Math.random().toString(36).slice(2)}`,name,roll,course,subjects:marks,total,percentage:(total/3).toFixed(2),status:marks.every(s=>s.marks>=35)?'Pass':'Fail',date:new Date().toLocaleDateString()};try{all.push(student);save(all)}catch{$('error').textContent='Could not save data. Check browser storage settings.';return}console.log('Student JSON:',JSON.stringify(student));showResult(student);render();event.target.reset();$('result').scrollIntoView({behavior:'smooth'})});
$('search').addEventListener('input',render);$('clearAll').addEventListener('click',()=>{if(load().length&&confirm('Delete ALL saved student records?')){localStorage.removeItem(KEY);render();$('result').hidden=true}});$('print').addEventListener('click',()=>window.print());render();
